SELECT * FROM dbo.Admins
SELECT * FROM dbo.Categories
SELECT * FROM dbo.CategoryProduct
SELECT * FROM dbo.Customers
SELECT * FROM dbo.OrderDetails
SELECT * FROM dbo.Orders
SELECT * FROM dbo.ProductInfos
SELECT * FROM dbo.Products
SELECT * FROM dbo.ProductSuppliers
SELECT * FROM dbo.ShippingInfos
SELECT * FROM dbo.ShoppingCarts
SELECT * FROM dbo.Users